fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
  symlinks:
    nscd: "#{source_dir}"
    external: "#{source_dir}/spec/external-resources/external"
