name 'ghoneycutt-nscd'
version '0.1.0'
source 'git://github.com/ghoneycutt/puppet-module-nscd.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'put a summary here'
description 'put a description here'
project_page 'https://github.com/ghoneycutt/puppet-module-nscd'

dependency 'puppetlabs/stdlib', '3.2.x'
